function test(obj)
% PURPOSE : Script for testing BPF
% INPUT : - obj          = @TrackerBPF object
% AUTHORS: Kenji Okuma
% DATE: January 2007
% =========================================================================

obj = set(obj, ...
    'img_width', 320, 'img_height', 240, ...
    'hsv_lambda', -20, ...
    'hsv_num_box', 2, ...
    'prior_noise_cov', [5 0 0; 0 5 0; 0 0 1]);

demo(obj, ...
    'name', 'test1', ...
    'BPF_alpha', .5, ...    
    'pc_num', 30);
