function detector_options = init_options(obj)
% PURPOSE : initialize parameters for detector
% INPUT : - obj = the @TrackerBPF object
% OUTPUT : - detector_options = initialized parameters for detector
% AUTHOR: Kenji Okuma
% DATE: January 2007
% =========================================================================


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% parameters of detector
% change here please
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%
% Do not change these
%%%%%%%%%%%%%%%%%%%%%%%%
g_repeats = 1;
g_useConfMap = 0;
g_printOverlaps = 0;
%%%%%%%%%%%%%%%%%%%%%%%%

% the detector has 23 layers and each layer has its threshold (>= 0.5)
% that is set manually.
cascadeThresh = [0.5 0.5 0.5 0.5 0.51 0.51 0.51 0.52 0.52 0.52 ...
				 0.53 0.53 0.53 0.53 0.53 0.53 0.54 0.54 0.54 0.54 ...
				 0.54 0.54 0.54];
detector_options = struct( ...
	'g_cascadeThresh', cascadeThresh, ...
    'g_imgWidth', obj.img_width, ...
    'g_imgHeight', obj.img_height, ...
    'g_useConfMap', g_useConfMap, ...
    'g_printOverlaps', g_printOverlaps, ...
    'g_minScale', 1.0, ...
    'g_maxScale', 2.5, ...
    'g_scaleFactor', 1.25, ...
    'g_delta', 2.0, ...
    'g_verbosity', 0, ...
    'g_repeats', g_repeats);
		
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

